# Generated by Django 5.0.6 on 2024-05-28 20:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentrecord",
            name="customer_last_name",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="paymentrecord",
            name="customer_name",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
