# Generated by Django 5.0.6 on 2024-05-28 20:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0003_paymentrecord_customer_last_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentrecord",
            name="customer_last_name",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="paymentrecord",
            name="customer_name",
            field=models.CharField(max_length=250),
        ),
    ]
