# Generated by Django 5.0.6 on 2024-06-01 20:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointment", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(default="in-progress", max_length=150),
        ),
    ]
