# Generated by Django 5.0.6 on 2024-06-02 15:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointment", "0003_alter_appointment_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="appointment",
            old_name="when",
            new_name="date",
        ),
        migrations.AddField(
            model_name="appointment",
            name="time",
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
