# Generated by Django 5.0.6 on 2024-06-02 17:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointment", "0004_rename_when_appointment_date_appointment_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="date",
            field=models.DateField(),
        ),
    ]
