# Generated by Django 5.0.6 on 2024-06-02 19:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointment", "0005_alter_appointment_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="comments",
            field=models.TextField(default=""),
        ),
    ]
