# Generated by Django 5.0.6 on 2024-06-02 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointment", "0006_alter_appointment_comments"),
        ("barber", "0001_initial"),
        ("service", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="barber",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="barber_appointments",
                to="barber.barber",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="comments",
            field=models.TextField(default=" "),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="service_appointments",
                to="service.service",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_appointments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
