# Generated by Django 5.0.6 on 2024-06-02 21:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointment", "0008_alter_appointment_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="email",
            field=models.EmailField(
                default=django.utils.timezone.now,
                max_length=254,
                verbose_name="customer email",
            ),
            preserve_default=False,
        ),
    ]
