# Generated by Django 5.0.6 on 2024-06-08 16:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("appointment", "0011_appointment_event_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="event_id",
        ),
    ]
