# Generated by Django 5.0.6 on 2024-06-08 17:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointment", "0012_remove_appointment_event_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="event_id",
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
